2023-11-11 11:08:33,298 INFO === (START PROGRAM) ===
2023-11-11 11:08:33,298 INFO Иницилизация [CLASS] UserFlow
2023-11-11 11:08:33,298 ERROR {Exception()}
2023-11-11 11:09:35,657 INFO === (START PROGRAM) ===
2023-11-11 11:09:35,657 INFO Иницилизация [CLASS] UserFlow
2023-11-11 11:09:35,657 ERROR 
2023-11-11 11:10:32,630 INFO === (START PROGRAM) ===
2023-11-11 11:10:32,630 INFO Иницилизация [CLASS] UserFlow
2023-11-11 11:10:32,630 ERROR Exception
Traceback (most recent call last):
  File "/home/semyon/адский проект/main.py", line 6, in <module>
    raise Exception
Exception
2023-11-11 11:12:35,760 INFO === (START PROGRAM) ===
2023-11-11 11:12:35,760 INFO Иницилизация [CLASS] UserFlow
2023-11-11 11:12:35,760 INFO === (END PROGRAM) ===
2023-11-11 11:55:10,691 INFO === (START PROGRAM) ===
2023-11-11 11:55:10,706 INFO === (END PROGRAM) ===
2023-11-11 11:56:16,343 INFO === (START PROGRAM) ===
2023-11-11 11:56:16,356 ERROR Exception
Traceback (most recent call last):
  File "/home/semyon/адский проект/main.py", line 5, in <module>
    UserFlow()
  File "/home/semyon/адский проект/project/__init__.py", line 7, in __init__
    self.settings.save("test", 123)
  File "/home/semyon/адский проект/project/settings.py", line 18, in save
    data = self._load_json()
  File "/home/semyon/адский проект/project/settings.py", line 12, in _load_json
    with open(self._path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'settings.json'
2023-11-11 11:56:16,357 INFO === (END PROGRAM) ===
2023-11-11 11:56:23,535 INFO === (START PROGRAM) ===
2023-11-11 11:56:23,545 ERROR Exception
Traceback (most recent call last):
  File "/home/semyon/адский проект/main.py", line 5, in <module>
    UserFlow()
  File "/home/semyon/адский проект/project/__init__.py", line 7, in __init__
    self.settings.save("test", 123)
  File "/home/semyon/адский проект/project/settings.py", line 18, in save
    data = self._load_json()
  File "/home/semyon/адский проект/project/settings.py", line 12, in _load_json
    with open(self._path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'settings.json'
2023-11-11 11:56:23,546 INFO === (END PROGRAM) ===
2023-11-11 11:56:48,839 INFO === (START PROGRAM) ===
2023-11-11 11:56:48,851 INFO [Settings] [save] successfully saved
2023-11-11 11:56:48,852 INFO [Settings] [load] successfully loaded
2023-11-11 11:56:48,852 INFO Иницилизация [CLASS] UserFlow
2023-11-11 11:56:48,852 INFO === (END PROGRAM) ===
2023-11-11 11:57:17,244 INFO === (START PROGRAM) ===
2023-11-11 11:57:17,258 INFO [Settings] [save] successfully saved
2023-11-11 11:57:17,259 INFO [Settings] [load] successfully loaded
2023-11-11 11:57:17,260 INFO Иницилизация [CLASS] UserFlow
2023-11-11 11:57:17,260 INFO === (END PROGRAM) ===
2023-11-11 14:16:59,616 INFO === (START PROGRAM) ===
2023-11-11 14:16:59,628 INFO [Settings] [save] successfully saved
2023-11-11 14:16:59,628 INFO [Settings] [load] successfully loaded
2023-11-11 14:16:59,628 INFO Иницилизация [CLASS] UserFlow
2023-11-11 14:16:59,628 INFO === (END PROGRAM) ===
2023-11-11 16:32:28,310 INFO === (START PROGRAM) ===
2023-11-11 16:33:02,281 INFO === (END PROGRAM) ===
2023-11-11 16:36:14,452 INFO === (START PROGRAM) ===
2023-11-11 16:36:14,588 ERROR Exception
Traceback (most recent call last):
  File "/home/semyon/адский проект/main.py", line 13, in <module>
    main()
  File "/home/semyon/адский проект/main.py", line 8, in main
    window = ExampleApp()  # Создаём объект класса ExampleApp
  File "/home/semyon/адский проект/project/__init__.py", line 10, in __init__
    self.add_project.clicked(self.browse_folder)
TypeError: native Qt signal is not callable
2023-11-11 16:36:14,589 INFO === (END PROGRAM) ===
2023-11-11 16:36:17,368 INFO === (START PROGRAM) ===
2023-11-11 16:36:17,463 ERROR Exception
Traceback (most recent call last):
  File "/home/semyon/адский проект/main.py", line 13, in <module>
    main()
  File "/home/semyon/адский проект/main.py", line 8, in main
    window = ExampleApp()  # Создаём объект класса ExampleApp
  File "/home/semyon/адский проект/project/__init__.py", line 10, in __init__
    self.add_project.clicked(self.browse_folder)
TypeError: native Qt signal is not callable
2023-11-11 16:36:17,464 INFO === (END PROGRAM) ===
2023-11-11 16:36:33,417 INFO === (START PROGRAM) ===
2023-11-11 16:37:08,634 INFO === (END PROGRAM) ===
2023-11-11 16:53:45,286 INFO === (START PROGRAM) ===
2023-11-11 16:53:54,882 INFO === (END PROGRAM) ===
2023-11-11 16:54:06,255 INFO === (START PROGRAM) ===
2023-11-11 16:54:08,598 INFO === (END PROGRAM) ===
2023-11-11 16:54:15,750 INFO === (START PROGRAM) ===
2023-11-11 16:54:22,349 INFO === (END PROGRAM) ===
2023-11-11 16:54:59,123 INFO === (START PROGRAM) ===
2023-11-11 16:55:23,587 INFO === (END PROGRAM) ===
2023-11-11 17:02:08,640 INFO === (START PROGRAM) ===
2023-11-11 17:02:36,280 INFO === (END PROGRAM) ===
2023-11-11 17:07:57,296 INFO === (START PROGRAM) ===
2023-11-11 17:08:22,985 INFO === (END PROGRAM) ===
2023-11-11 18:40:03,252 INFO === (START PROGRAM) ===
2023-11-11 18:40:29,213 INFO === (END PROGRAM) ===
2023-11-11 18:41:20,169 INFO === (START PROGRAM) ===
2023-11-11 18:41:27,416 INFO === (END PROGRAM) ===
2023-11-11 18:41:44,757 INFO === (START PROGRAM) ===
2023-11-11 18:42:43,052 INFO === (END PROGRAM) ===
2023-11-11 18:42:59,421 INFO === (START PROGRAM) ===
2023-11-11 18:43:35,643 INFO === (END PROGRAM) ===
2023-11-11 18:45:37,714 INFO === (START PROGRAM) ===
2023-11-11 18:45:57,083 INFO === (END PROGRAM) ===
2023-11-11 18:46:36,201 INFO === (START PROGRAM) ===
2023-11-11 18:46:39,460 INFO === (END PROGRAM) ===
2023-11-11 18:47:25,019 INFO === (START PROGRAM) ===
2023-11-11 18:47:28,210 INFO === (END PROGRAM) ===
2023-11-11 18:47:42,914 INFO === (START PROGRAM) ===
2023-11-11 18:47:48,980 INFO === (END PROGRAM) ===
2023-11-11 18:48:49,315 INFO === (START PROGRAM) ===
2023-11-11 18:48:54,555 INFO === (END PROGRAM) ===
2023-11-11 18:49:10,957 INFO === (START PROGRAM) ===
2023-11-11 18:49:39,802 INFO === (END PROGRAM) ===
2023-11-11 19:16:09,171 INFO === (START PROGRAM) ===
2023-11-11 19:16:21,212 INFO === (END PROGRAM) ===
2023-11-11 19:16:52,613 INFO === (START PROGRAM) ===
2023-11-11 19:16:58,502 INFO === (END PROGRAM) ===
2023-11-11 19:17:46,213 INFO === (START PROGRAM) ===
2023-11-11 19:17:55,286 INFO === (END PROGRAM) ===
2023-11-11 19:18:38,110 INFO === (START PROGRAM) ===
2023-11-11 19:18:51,124 INFO === (END PROGRAM) ===
2023-11-11 19:21:53,066 INFO === (START PROGRAM) ===
2023-11-11 19:22:11,377 INFO === (END PROGRAM) ===
2023-11-11 19:22:44,531 INFO === (START PROGRAM) ===
2023-11-11 19:23:47,792 INFO === (END PROGRAM) ===
2023-11-11 19:24:03,326 INFO === (START PROGRAM) ===
2023-11-11 19:28:12,718 INFO === (END PROGRAM) ===
2023-11-11 19:28:15,143 INFO === (START PROGRAM) ===
2023-11-11 19:28:52,879 INFO === (END PROGRAM) ===
2023-11-11 19:34:51,194 INFO === (START PROGRAM) ===
2023-11-11 19:35:07,110 INFO === (END PROGRAM) ===
2023-11-11 20:03:23,414 INFO === (START PROGRAM) ===
2023-11-11 20:03:42,762 INFO === (END PROGRAM) ===
2023-11-11 20:03:56,290 INFO === (START PROGRAM) ===
2023-11-11 20:04:11,295 INFO === (END PROGRAM) ===
2023-11-11 20:07:27,001 INFO === (START PROGRAM) ===
2023-11-11 20:07:41,251 INFO === (END PROGRAM) ===
2023-11-11 20:07:48,989 INFO === (START PROGRAM) ===
2023-11-11 20:07:53,376 INFO === (END PROGRAM) ===
2023-11-11 20:10:29,439 INFO === (START PROGRAM) ===
2023-11-11 20:11:03,820 INFO === (END PROGRAM) ===
2023-11-11 20:11:28,098 INFO === (START PROGRAM) ===
2023-11-11 20:11:35,804 INFO === (END PROGRAM) ===
2023-11-11 20:12:17,533 INFO === (START PROGRAM) ===
2023-11-11 20:12:23,843 INFO === (END PROGRAM) ===
2023-11-11 20:12:41,708 INFO === (START PROGRAM) ===
2023-11-11 20:12:50,741 INFO === (END PROGRAM) ===
2023-11-11 20:20:24,587 INFO === (START PROGRAM) ===
2023-11-11 20:20:40,635 INFO === (END PROGRAM) ===
2023-11-11 20:21:43,587 INFO === (START PROGRAM) ===
2023-11-11 20:22:20,771 INFO === (END PROGRAM) ===
2023-11-11 20:23:41,492 INFO === (START PROGRAM) ===
2023-11-11 20:23:41,642 ERROR Exception
Traceback (most recent call last):
  File "/home/semyon/адский проект/main.py", line 13, in <module>
    main()
  File "/home/semyon/адский проект/main.py", line 8, in main
    window = ExampleApp()  # Создаём объект класса ExampleApp
  File "/home/semyon/адский проект/project/__init__.py", line 17, in __init__
    self.list_programs.itemClicked.connect(self.select_program)
AttributeError: 'ExampleApp' object has no attribute 'list_programs'
2023-11-11 20:23:41,643 INFO === (END PROGRAM) ===
2023-11-11 20:27:16,365 INFO === (START PROGRAM) ===
2023-11-11 20:27:29,262 INFO === (END PROGRAM) ===
2023-11-11 20:28:10,720 INFO === (START PROGRAM) ===
2023-11-12 10:35:05,055 INFO === (END PROGRAM) ===
2023-11-12 10:44:22,310 INFO === (START PROGRAM) ===
2023-11-12 10:44:22,418 ERROR Exception
Traceback (most recent call last):
  File "/home/semyon/адский проект/main.py", line 21, in <module>
    main2()
  File "/home/semyon/адский проект/main.py", line 16, in main2
    ui = Ui_MainWindow(logger=logger)
  File "/home/semyon/адский проект/project/autorun/__init__.py", line 14, in __init__
    self.setupUi(self)
  File "/home/semyon/адский проект/project/autorun/__init__.py", line 18, in setupUi
    MainWindow.setObjectName("MainWindow")
AttributeError: 'Ui_MainWindow' object has no attribute 'setObjectName'
2023-11-12 10:44:22,419 INFO === (END PROGRAM) ===
2023-11-12 10:45:20,151 INFO === (START PROGRAM) ===
2023-11-12 10:45:25,565 INFO === (END PROGRAM) ===
2023-11-12 10:48:14,432 INFO === (START PROGRAM) ===
2023-11-12 10:48:23,803 INFO === (END PROGRAM) ===
2023-11-12 10:48:55,166 INFO === (START PROGRAM) ===
2023-11-12 10:48:56,308 INFO CompletedProcess(args=['C:\\Program Files\\JetBrains\\PyCharm Community Edition 2023.2.1\\bin\\pycharm64.exe', 'D:\\Python\\Pycharm_Projects\\pyqt5'], returncode=127)
2023-11-12 10:49:00,371 INFO CompletedProcess(args=['C:\\Program Files (x86)\\Steam\\steam.exe', ''], returncode=2)
2023-11-12 10:49:02,945 INFO === (END PROGRAM) ===
2023-11-12 10:54:58,818 INFO === (START PROGRAM) ===
2023-11-12 10:54:58,823 INFO Иницилизация [CLASS] UserFlow
2023-11-12 10:55:00,745 INFO === (END PROGRAM) ===
2023-11-12 10:55:16,383 INFO === (START PROGRAM) ===
2023-11-12 10:55:16,387 INFO Иницилизация [CLASS] UserFlow
2023-11-12 10:55:18,064 INFO === (END PROGRAM) ===
2023-11-12 10:55:26,072 INFO === (START PROGRAM) ===
2023-11-12 10:55:26,077 INFO Иницилизация [CLASS] UserFlow
2023-11-12 10:55:28,360 INFO === (END PROGRAM) ===
2023-11-12 10:59:02,473 INFO === (START PROGRAM) ===
2023-11-12 10:59:02,477 INFO Иницилизация [CLASS] UserFlow
2023-11-12 10:59:04,240 INFO === (END PROGRAM) ===
2023-11-12 11:22:49,989 INFO === (START PROGRAM) ===
2023-11-12 11:22:49,990 INFO Иницилизация [CLASS] UserFlow
2023-11-12 11:22:51,152 INFO CompletedProcess(args=['C:\\Program Files\\JetBrains\\PyCharm Community Edition 2023.2.1\\bin\\pycharm64.exe', 'D:\\Python\\Pycharm_Projects\\pyqt5'], returncode=127)
2023-11-12 11:22:58,437 INFO === (END PROGRAM) ===
2023-11-12 11:23:18,225 INFO === (START PROGRAM) ===
2023-11-12 11:23:18,225 INFO Иницилизация [CLASS] UserFlow
2023-11-12 11:23:19,726 INFO CompletedProcess(args=['C:\\Program Files\\JetBrains\\PyCharm Community Edition 2023.2.1\\bin\\pycharm64.exe', 'D:\\Python\\Pycharm_Projects\\pyqt5'], returncode=127)
2023-11-12 11:23:22,925 INFO CompletedProcess(args=['C:\\Program Files (x86)\\Steam\\steam.exe', ''], returncode=2)
2023-11-12 11:23:33,055 INFO === (END PROGRAM) ===
